<a href="https://colab.research.google.com/github/adityajoshi020503/IIITH-ML-2024-25/blob/main/Linear_Algebra_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Linear Algebra Practice

In [1]:
import numpy as np
import matplotlib.pyplot as plt

###1. Vectors and Operations

In [4]:
#Creating Vectors
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [5]:
#Vector Addition
v_add = v1 + v2
print("Vector Addition:", v_add)

#Vector Subtraction
v_sub = v1 - v2
print("Vector Subtraction:", v_sub)

#Scalar multiplication
V_scalar = 2 * v1
print("Vector Multiplication:", V_scalar)

#Dot Product
dot_product = np.dot(v1, v2)
print("Dot Product:", dot_product)

#Cross Product
cross_product = np.cross(v1, v2)
print("Cross Product:", cross_product)

Vector Addition: [5 7 9]
Vector Subtraction: [-3 -3 -3]
Vector Multiplication: [2 4 6]
Dot Product: 32
Cross Product: [-3  6 -3]


###2. Matrix and Operations

In [8]:
# Creating a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [11]:
# Matrix addition
C_add = A + B
print("A + B:\n", C_add)

# Matrix subtraction
C_sub = A - B
print("A - B:\n", C_sub)

# Matrix multiplication
C_mul = np.dot(A, B)
print("A*B:\n", C_mul)


A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
A - B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
A*B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [12]:
# Transpose of matrix A
A_transpose = np.transpose(A)
print("Transpose of A:\n", A_transpose)


Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
# Determinant of matrix A
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: 0.0


In [15]:
# Inverse of matrix A

try:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
except np.linalg.LinAlgError:
    print("Matrix A is singular and does not have an inverse.")


Matrix A is singular and does not have an inverse.


In [16]:
# Eigenvalues and eigenvectors of matrix A
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:", eigenvalues)
print("Eigenvectors of A:\n", eigenvectors)

Eigenvalues of A: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors of A:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
